# Minor Paper AITEE

1) Update the weights of given neural network using perceptron learning for one iteration

In [7]:
import numpy as np

# inputs
x = np.array([[0.1],
            [0.2],
            [0.3],
            [0.4]])


#eta 
n=0.1

# weights
w = np.array([[0.25],
            [-0.2],
            [-0.3],
            [0.4]]
            )

# net
net = w.T @ x

# output
output = np.sign(net)

# desired output
d=1

# error
dw = n*(d-output)*x

# updated weight
w=w+dw

# print values
print("Updated Weights")
print(np.round(np.ravel(w), 5))

Updated Weights
[ 0.25 -0.2  -0.3   0.4 ]


2) Back Propagation of ax^2 - b =0; given weights, a=1, b=7; eta=0.5

In [8]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

def d_sigmoid(x):
    return x*(1-x)

In [10]:
# inputs and target
a, b = 2.0, 7.0
x=np.array([[a] ,
            [b]])

# desired values
root_val = np.sqrt(b/a)
t = np.array([[root_val],
     [-root_val]])

# Initial Weights
W_ji = np.array([[-0.1, 0.9, -0.2],
                [0.8, -0.3, 0.1]])

W_kj = np.array([[-0.2, 0.4],
                [0.8, -0.6 ],
                [-0.5, 0.9]])

eta =0.5
iterations=2

BPA

In [14]:
for it in range(1, iterations+1):

    # Forward Pass

    net_j = np.dot(W_ji.T, x)
    O_j = sigmoid(net_j)

    net_k = np.dot(W_kj.T, O_j) 
    O_k = sigmoid(net_k)


    # BackWard Pass

    delta_k = (t- O_k)*d_sigmoid(O_k)
    dW_kj = eta * O_j @ delta_k.T

    delta_j = np.dot(W_kj, delta_k) * d_sigmoid(O_j)
    dW_ji = eta * np.dot(x, delta_j.T)


    # Updated Weights
    W_kj +=dW_kj
    W_ji +=dW_ji

    # Print Values
    print(f"--- Iteration {it} ---")
    print(f"Outputs (O_k):\n{O_k.ravel()}")
    print(f"Updated W_kj:\n{W_kj}")
    print(f"Updated W_ji:\n{W_ji}\n")


--- Iteration 1 ---
Outputs (O_k):
[0.46359553 0.65923012]
Updated W_kj:
[[-0.02581507  0.11709426]
 [ 0.8744605  -0.72093642]
 [-0.39948884  0.73675291]]
Updated W_ji:
[[-0.10133089  1.05180246 -0.36782111]
 [ 0.79534188  0.23130862 -0.48737388]]

--- Iteration 2 ---
Outputs (O_k):
[0.69464258 0.35987412]
Updated W_kj:
[[ 0.09834694 -0.13864683]
 [ 0.99625989 -0.97181115]
 [-0.39754763  0.73275453]]
Updated W_ji:
[[-0.10163965  1.06536464 -0.37514791]
 [ 0.79426121  0.27877625 -0.5130177 ]]

